spring:
  application:
    name: tracing
  main:
    banner-mode: "off"

logging:
  level:
    root: info
    com.github.cyberpunkperson.tracing: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X] %logger{80} %msg%n'

kafka:
  default:
    url:  localhost:29092
    consumer:
      group-id: ${spring.application.name}
    producer:
      acks: all
  sources:
    dc:
      url: ${kafka.default.url}
      consumer:
        group-id: ${kafka.default.consumer.group-id}
        properties:
          auto.offset.reset: latest
    marvel:
      url: ${kafka.default.url}
      consumer:
        group-id: ${kafka.default.consumer.group-id}
        properties:
          auto.offset.reset: latest
  topics:
    dc:
      name: dc-news
    marvel:
      name: marvel-news
    news-target:
      name: news-target